name: dynamic_intl_generator
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  dart_style: ^2.2.3

dev_dependencies:
  flutter_lints: ^1.0.0
