name: dynamic_intl_generator
description: A new Flutter package project.
version: 0.0.2

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  args: ^2.3.0
  dart_style: ^2.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
